name: gps_software
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_datepicker: ^29.1.35
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  package_info_plus: ^8.0.2
  share_plus: ^10.0.2
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  firebase_core: ^4.2.1
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0
  intl: ^0.18.1
  device_info_plus: ^11.2.0
  fluttertoast: ^8.2.8
  flutter_tts: ^4.0.2
  path_provider: ^2.1.1
  sound_mode:
    path: package/sound_mode-3.0.0
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  flutter_dotenv: ^6.0.0
  flutter_downloader: ^1.11.8
  in_app_review: ^2.0.11
  flutter_svg: ^2.2.2

dependency_overrides:
  intl: ^0.18.1
  google_maps_flutter_platform_interface: <2.15.0
  # webf: ^0.16.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.1.0


# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/app_logo.png"
#   min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  fonts:
  - family: Dmsans
    fonts:
      - asset: assets/fonts/DMSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/DMSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/DMSans-Bold.ttf
        weight: 700
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/ringtone/
    - shorebird.yaml
    - .env
