// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // TODO(Lyokone): Remove when FlutterFire CLI updated
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMNPiHRw-E561xySy6hN9V3DXusGenrK4',
    appId: '1:781126975504:web:508acb68f38c04deab0a95',
    messagingSenderId: '781126975504',
    projectId: 'twings-324f4',
    authDomain: 'twings-324f4.firebaseapp.com',
    databaseURL: 'https://twings-324f4.firebaseio.com',
    storageBucket: 'twings-324f4.firebasestorage.app',
    measurementId: 'G-DDKPP13PX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArPO00VX_f803MA4TF9HxLRBkulSdVGf0',
    appId: '1:781126975504:android:a2d206f59e9eee1f',
    messagingSenderId: '781126975504',
    projectId: 'twings-324f4',
    databaseURL: 'https://twings-324f4.firebaseio.com',
    storageBucket: 'twings-324f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlX9KvHjl3_wYX8rMfNheUsJQKvFO02B0',
    appId: '1:781126975504:ios:9b3b3ef0309f1d51ab0a95',
    messagingSenderId: '781126975504',
    projectId: 'twings-324f4',
    databaseURL: 'https://twings-324f4.firebaseio.com',
    storageBucket: 'twings-324f4.firebasestorage.app',
    androidClientId: '781126975504-rca9qeqa17dae1utm40it7q96ct8r27t.apps.googleusercontent.com',
    iosClientId: '781126975504-oo7p3tig3idcle7g536svfqin8efk3j6.apps.googleusercontent.com',
    iosBundleId: 'com.Twings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDooSUGSf63Ghq02_iIhtnmwMDs4HlWS6c',
    appId: '1:406099696497:ios:acd9c8e17b5e620e3574d0',
    messagingSenderId: '406099696497',
    projectId: 'flutterfire-e2e-tests',
    databaseURL:
        'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutterfire-e2e-tests.appspot.com',
    androidClientId:
        '406099696497-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
    iosClientId:
        '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.tests',
  );
}